# Generated by Django 5.0.1 on 2024-01-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeuInss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('sobrenome', models.CharField(max_length=70)),
                ('cpf', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=14)),
            ],
        ),
    ]
