# Generated by Django 5.0.1 on 2024-01-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reunioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=50)),
                ('nome_participante', models.CharField(max_length=120)),
                ('data', models.DateField()),
            ],
        ),
    ]
